/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package institute.of.studies;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import javax.swing.RowFilter;



/**
 *
 * @author Kalani
 */
public class Employeeregistation extends javax.swing.JFrame {
    private static final String username="root";
    private static final String password="";
    private static final String dataConn="jdbc:mysql://localhost:3306/colombo_studies";
    
    Connection sqlConn=null;
    PreparedStatement pst = null;
    ResultSet rs=null;
    int n1,n2;

    /**
     * Creates new form HRregistation
     */
    public Employeeregistation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt3 = new javax.swing.JTextField();
        txt2 = new javax.swing.JTextField();
        txt11 = new javax.swing.JTextField();
        txt4 = new javax.swing.JTextField();
        txt6 = new javax.swing.JTextField();
        txt1 = new javax.swing.JTextField();
        txt8 = new javax.swing.JTextField();
        txt7 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txt10 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt5 = new javax.swing.JTextField();
        txt12 = new javax.swing.JTextField();
        txt9 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txt13 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Sitka Text", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(199, 126, 29));
        jLabel1.setText("Registration ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(270, 30, 323, 40);

        jLabel2.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Employee Number");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 100, 186, 30);

        jLabel3.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Employee Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 160, 171, 23);

        jLabel4.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Employee Address");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 220, 186, 33);

        jLabel5.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Basic Salary ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(440, 420, 140, 27);

        jLabel6.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Email");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 280, 149, 29);

        jLabel7.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Department");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 470, 140, 30);

        jLabel8.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Age");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(440, 110, 141, 31);

        jLabel9.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Position ");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(440, 170, 166, 36);

        jLabel10.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Gender");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(440, 240, 114, 27);
        getContentPane().add(txt3);
        txt3.setBounds(250, 220, 140, 26);
        getContentPane().add(txt2);
        txt2.setBounds(250, 160, 140, 26);
        getContentPane().add(txt11);
        txt11.setBounds(630, 360, 130, 26);
        getContentPane().add(txt4);
        txt4.setBounds(250, 280, 140, 26);
        getContentPane().add(txt6);
        txt6.setBounds(250, 410, 140, 26);
        getContentPane().add(txt1);
        txt1.setBounds(250, 100, 140, 26);
        getContentPane().add(txt8);
        txt8.setBounds(630, 170, 130, 26);
        getContentPane().add(txt7);
        txt7.setBounds(630, 110, 130, 26);

        jButton1.setBackground(new java.awt.Color(0, 102, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Add Data");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(120, 580, 120, 31);

        jButton2.setBackground(new java.awt.Color(0, 102, 102));
        jButton2.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Update Details ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(250, 580, 150, 31);

        jButton3.setBackground(new java.awt.Color(0, 102, 102));
        jButton3.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Delete Data");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(420, 580, 140, 31);

        jButton4.setBackground(new java.awt.Color(0, 102, 102));
        jButton4.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Filter");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(580, 580, 90, 31);

        jButton6.setBackground(new java.awt.Color(0, 0, 204));
        jButton6.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Back");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(30, 580, 76, 31);

        jLabel11.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("EPF Number ");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(440, 300, 135, 31);
        getContentPane().add(txt10);
        txt10.setBounds(630, 300, 130, 26);

        jLabel12.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Contact Number");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(20, 340, 177, 27);

        jLabel13.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Status ");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(440, 360, 140, 27);
        getContentPane().add(txt5);
        txt5.setBounds(250, 340, 140, 26);
        getContentPane().add(txt12);
        txt12.setBounds(630, 420, 130, 26);

        txt9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt9ActionPerformed(evt);
            }
        });
        getContentPane().add(txt9);
        txt9.setBounds(630, 230, 120, 30);

        jLabel15.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Date Of Birth ");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(20, 410, 140, 30);
        getContentPane().add(txt13);
        txt13.setBounds(250, 470, 140, 26);

        jButton5.setBackground(new java.awt.Color(0, 204, 204));
        jButton5.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 0, 0));
        jButton5.setText("Refresh ");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(710, 580, 90, 27);

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\Kalani\\Pictures\\java\\my8.jpg")); // NOI18N
        jLabel14.setText("jLabel14");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(0, 0, 860, 640);

        setSize(new java.awt.Dimension(874, 645));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (txt1.getText().isEmpty() || txt2.getText().isEmpty() || txt3.getText().isEmpty() ||
        txt4.getText().isEmpty() || txt5.getText().isEmpty() || txt6.getText().isEmpty() ||
        txt7.getText().isEmpty() || txt8.getText().isEmpty() || txt9.getText().isEmpty() ||
        txt10.getText().isEmpty()|| txt11.getText().isEmpty() || txt12.getText().isEmpty() || txt13.getText().isEmpty()) {
        
        JOptionPane.showMessageDialog(this, "Please fill in all fields", "Validation Error", JOptionPane.ERROR_MESSAGE);
        return; // Exit the method if validation fails
}
        try{
            Class.forName("com.mysql.jdbc.Driver");
            sqlConn=DriverManager.getConnection(dataConn,username,password);
            pst=sqlConn.prepareStatement("insert into  employee_table(ID,name,address,email,contact_num,DOB,age,position,gender,EPF_NO,Status,Basicsalary,department_name)value(?,?,?,?,?,?,?,?,?,?,?,?,?)");
            pst.setString(1,txt1.getText());
            pst.setString(2,txt2.getText());
            pst.setString(3,txt3.getText());
            pst.setString(4,txt4.getText());
            pst.setString(5,txt5.getText());
            pst.setString(6,txt6.getText());
            pst.setString(7,txt7.getText());
            pst.setString(8,txt8.getText());
            pst.setString(9,txt9.getText());
            pst.setString(10,txt10.getText());
            pst.setString(11,txt11.getText());
            pst.setString(12,txt12.getText());
            pst.setString(13,txt13.getText());  
            

           pst.executeUpdate();
           JOptionPane.showMessageDialog(this, "Record added successful");
            
            
            
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex);
        
        }  
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
                if (txt1.getText().isEmpty() || txt2.getText().isEmpty() || txt3.getText().isEmpty() ||
        txt4.getText().isEmpty() || txt5.getText().isEmpty() || txt6.getText().isEmpty() ||
        txt7.getText().isEmpty() || txt8.getText().isEmpty() || txt9.getText().isEmpty() ||
        txt10.getText().isEmpty()|| txt11.getText().isEmpty() || txt12.getText().isEmpty() || txt13.getText().isEmpty()) {
        
        JOptionPane.showMessageDialog(this, "Please fill in all required fields", "Validation Error", JOptionPane.ERROR_MESSAGE);
        return; // Exit the method if validation fails
}
        
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            sqlConn=DriverManager.getConnection(dataConn,username,password);
            pst=sqlConn.prepareStatement("UPDATE employee_table SET ID=?,name=?,address=?,email=?,contact_num=?,DOB=?,age=?,position=?,gender=?,EPF_NO=?,Status=?,Basicsalary=?,department_name=? WHERE ID=?");
            pst.setString(1,txt1.getText());
            pst.setString(2,txt2.getText());
            pst.setString(3,txt3.getText());
            pst.setString(4,txt4.getText());
            pst.setString(5,txt5.getText());
            pst.setString(6,txt6.getText());
            pst.setString(7,txt7.getText());
            pst.setString(8,txt8.getText());
            pst.setString(9,txt9.getText());
            pst.setString(10,txt10.getText());
            pst.setString(11,txt11.getText());
            pst.setString(12,txt12.getText());
            pst.setString(13,txt13.getText());
            pst.setString(14,txt1.getText());    
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this,"Record updated successfully");
            
            
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this , ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
    // Validate that the ID is not empty
    String id = txt1.getText().trim();
    if (id.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter an ID to delete.");
        return; // Exit the method if the ID is empty
    }

    // Validate that the ID is a number
    try {
        Integer.parseInt(id);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Please enter a valid numeric ID.");
        return; // Exit the method if the ID is not a number
    }

    Class.forName("com.mysql.jdbc.Driver");
    sqlConn = DriverManager.getConnection(dataConn, username, password);

    pst = sqlConn.prepareStatement("DELETE FROM employee_table WHERE ID=?");
    pst.setString(1, id);

    int rowsAffected = pst.executeUpdate();

    if (rowsAffected > 0) {
        JOptionPane.showMessageDialog(this, "Record deleted successfully");
    } else {
        JOptionPane.showMessageDialog(this, "No record found with the specified ID");
    }

} catch (Exception ex) {
    JOptionPane.showMessageDialog(this, ex.getMessage());
} finally {
    // Close resources (pst, sqlConn) in a finally block to ensure they are closed even if an exception occurs.
    // Note: You should handle SQLException properly in a real-world scenario.
    try {
        if (pst != null) {
            pst.close();
        }
        if (sqlConn != null) {
            sqlConn.close();
        }
    } catch (SQLException e) {
        e.printStackTrace(); // Handle the exception properly in a real-world scenario.
    }
}

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         try{
            Class.forName("com.mysql.jdbc.Driver");
            sqlConn=DriverManager.getConnection(dataConn,username,password);
            pst=sqlConn.prepareStatement("select ID,name,address,email,contact_num,DOB,age,position,gender,EPF_NO,Status,Basicsalary,department_name from employee_table WHERE ID=?");
            int ID=Integer.parseInt(txt1.getText());
            pst.setInt(1,ID);
            rs=pst.executeQuery();
            if(rs.next()==false){
                JOptionPane.showMessageDialog(this, "Please enter a valid ID (numeric value).");
                txt1.setText("");
                txt2.setText("");
                txt3.setText("");
                txt4.setText("");
                txt5.setText("");
                txt6.setText("");
                txt7.setText("");
                txt8.setText("");
                txt9.setText("");
                txt10.setText("");
                txt11.setText("");
                txt12.setText("");
                txt13.setText("");
            }
            else{
                
                txt2.setText(rs.getString("name"));
                txt3.setText(rs.getString("address"));
                txt4.setText(rs.getString("email"));
                txt5.setText(rs.getString("contact_num"));
                txt6.setText(rs.getString("DOB"));
                txt7.setText(rs.getString("age"));
                txt8.setText(rs.getString("position"));
                txt9.setText(rs.getString("gender"));
                txt10.setText(rs.getString("EPF_NO"));
                txt11.setText(rs.getString("Status"));
                txt12.setText(rs.getString("Basicsalary"));
                txt13.setText(rs.getString("department_name"));
                
            }
                        
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this , "Database connection error");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        manager_homepage Employeeregistation=new  manager_homepage();
        Employeeregistation.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void txt9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt9ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
                txt1.setText(null);
                txt2.setText(null);
                txt3.setText(null);
                txt4.setText(null);
                txt5.setText(null);
                txt6.setText(null);
                txt7.setText(null);
                txt8.setText(null);
                txt9.setText(null);
                txt10.setText(null);
                txt11.setText(null);
                txt12.setText(null);
                txt13.setText(null);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employeeregistation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employeeregistation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employeeregistation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employeeregistation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employeeregistation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt10;
    private javax.swing.JTextField txt11;
    private javax.swing.JTextField txt12;
    private javax.swing.JTextField txt13;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txt3;
    private javax.swing.JTextField txt4;
    private javax.swing.JTextField txt5;
    private javax.swing.JTextField txt6;
    private javax.swing.JTextField txt7;
    private javax.swing.JTextField txt8;
    private javax.swing.JTextField txt9;
    // End of variables declaration//GEN-END:variables
}
